name: Citywide Digital
favicon: null
layout_spectrum: 0.6012240371201187
typography_spectrum: 0.9454977351706475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.20882117142900825
  lightness: 0.968054264318198
  saturation: 0.20107261068187654
  rhythmicContrast: 0.33182678185403347
purpose: []
